[package]
name = "contract"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.16.0" }
starknet = "2.11.2"

[dev-dependencies]
cairo_test = "2.11.2"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.40.0" }

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true

[cairo]
sierra-replace-ids = false
inlining-strategy = 2