[package]
name = "circuit"
type = "bin"
authors = []
compiler_version = ">=1.0.0"

[dependencies]
zkemail = { tag = "chore/update-dependencies", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
